[package]
name = "stipe"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Set-theoretic structural type system and solver"
repository = "https://github.com/Past9/stipe"

[dependencies]
bumpalo = { version = "3.19.0", features = [ "collections"] }
